name: invertible
version: 2.0.0-nullsafety.0
description: A Dart library for defining invertible functions and their compositions
repository: https://github.com/dkin-om/invertible-dart.git
issue_tracker: https://github.com/dkin-om/invertible-dart/issues
homepage: https://github.com/dkin-om/invertible-dart#readme
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  equatable: ^2.0.0
dev_dependencies:
  test: ^1.14.4
