name: invertible
version: 1.0.0-beta.1
description: A Dart library
repository: https://github.com/dkin-om/invertible-dart.git
issue_tracker: https://github.com/dkin-om/invertible-dart/issues
homepage: https://github.com/dkin-om/invertible-dart#readme
environment:
  sdk: '>=2.8.1 <3.0.0'
dev_dependencies:
  test: ^1.14.4
